### ISSUE TITLE
what is  `tf.train.start_queue_runners`for? 

### ISSUE THREAD

**Issue by hongjic** [philipperemy/tensorflow-fifo-queue-example#1]
I delete that line and that still works. I think in this example this is not necessary. Do I miss something?

By the way, `range(1e9)` make me restart my laptop several times until I found it out... I think a smaller number would be enough for this experiment..

**Comment by philipperemy** [comment]
Fixed with b9a84282f92995cb12b51ebcffe0cdb7d30356ac
